### ISSUE TITLE
Merge FDR output into vue component

### ISSUE THREAD

**Issue by t0mdavid-m** [t0mdavid-m/FLASHViewer#12]
Currently the FDR output is displayed in a single tab. However, it should be moved into the `vue.js` component, together with the other visualizations.

### Things to consider:

- The FDR information might not be reported in all cases. The visualization should be able to handle the absence of this output (i.e. either block the respective visualization components or display some sort of empty output)

**Comment by Ayesha-Feroz** [comment]
I created FDR_plotly.vue to display the FDR plot inside the Viewer. The plot is now successfully rendered within the Vue component and the FLASHDeconv viewer.
Tom is currently refactoring some parts of the codebase. Once these adjustments are complete, I will test the FDR plot using a real parsed file from FLASHDeconv.
For reference, see this PR: https://github.com/t0mdavid-m/openms-streamlit-vue-component/pull/6
